# Generated by Django 5.1.4 on 2024-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tituloArticulo",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "descripcionArticulo",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "fechaArticulo",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "temaArticulo",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
        ),
    ]
