# Generated by Django 5.1.4 on 2024-12-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikiApp", "0003_alter_articulo_descripcionarticulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="temaR",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wikiApp.tema",
            ),
        ),
    ]
